 const taskStaus={
  'daily':[
    {
      name:'待处理',
      type:'NO_CONFIRM',
      color:'#FF6666'
    },
    {
      name:'处理中',
      type:'REPAIRING',
      color:'#FFAA00'
    },
    {
      name:'已驳回',
      type:'OVERRULE',
      color:'#7D72FA'
    },
    {
      name:'待确认',
      type:'REPAIR_COMPLETE',
      color:'#00AAFF'
    },
    {
      name:'已完成',
      type:'SCORE_COMPLETE',
      color:'#2BD680'
    },
    {
      name:'已撤销',
      type:'REVOKE',
      color:'#BCC1CC'
    }
  ],
  'maintain':[
    {
      name:'待保养',
      type:'NO_CONFIRM',
      color:'#FF6666'
    },
    {
      name:'保养中',
      type:'REPAIRING',
      color:'#FFAA00'
    },
    {
      name:'已驳回',
      type:'OVERRULE',
      color:'#7D72FA'
    },
    {
      name:'待确认',
      type:'REPAIR_COMPLETE',
      color:'#00AAFF'
    },
    {
      name:'已完成',
      type:'SCORE_COMPLETE',
      color:'#2BD680'
    },
   ],
  'repair':[
     {
      name:'待处理',
      type:'NO_CONFIRM',
      color:'#FF6666'
    },
    {
      name:'处理中',
      type:'REPAIRING',
      color:'#FFAA00'
    },
    {
      name:'已驳回',
      type:'OVERRULE',
      color:'#7D72FA'
    },
    {
      name:'待确认',
      type:'REPAIR_COMPLETE',
      color:'#00AAFF'
    },
    {
      name:'已完成',
      type:'SCORE_COMPLETE',
      color:'#2BD680'
    },
    {
      name:'已撤销',
      type:'REVOKE',
      color:'#BCC1CC'
    }
  ]
      
}
const requestParams={
  maintain:'maintainTaskStatus',
  repair:'taskStatus',
  daily:'taskStatus'
}
export  {taskStaus,requestParams}
 
